# appveyor CI, likely soon fully replaced by new Github Workflows CI (see .github/workflows/ci.yml)
#   runs on private appveyor account (haas) - not ideal for public repository. also slower than github.
image: Visual Studio 2022
environment:
  timeout: 15000
  matrix:
    # - nodejs_version: "12"
    - nodejs_version: "24"
platform:
  # - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  # - npm run fix-memory-limit # doesn't work anymore with node 24, probably not neessary
  - npm install
# build_script: # included in npm install
#   - npm run lint
#   - npm run build
test_script:
  - npm run test
